name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: autograder test
      id: autograder-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: autograder test
        setup-command: pip install pytest
        command: python3 test.py
        timeout: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        AUTOGRADER-TEST_RESULTS: "${{steps.autograder-test.outputs.result}}"
      with:
        runners: autograder-test
